### ISSUE TITLE
gsmevil crash

### ISSUE THREAD

**Issue by supashot** [ninjhacks/gsmevil2#10]
Installing using gsmevil2 works fine till it seems to crash after a certain volume of data entries.
Traceback (most recent call last):                                                                                                                                                        
  File "GsmEvil.py", line 285, in <module>                                                                                                                                                
    GsmSniffer.sniffer()                                                                                                                                                                  
  File "GsmEvil.py", line 56, in sniffer                                                                                                                                                  
    ImsiEvil().get_imsi(packet)                                                                                                                                                           
  File "GsmEvil.py", line 129, in get_imsi                                                                                                                                                
    self.filter_imsi()                                                                                                                                                                    
  File "GsmEvil.py", line 109, in filter_imsi                                                                                                                                             
    imsi_live_db[self.imsi] = {"id" : self.imsi_id,"tmsi" : self.tmsi, "mcc" : self.mcc, "mnc" : self.mnc}                                                                                
AttributeError: 'ImsiEvil' object has no attribute 'imsi_id'                                                                                                                              
^CException ignored in: <module 'threading' from '/usr/lib/python3.8/threading.py'>                                                                                                       
Traceback (most recent call last):                                                                                                                                                        
  File "/usr/lib/python3.8/threading.py", line 1388, in _shutdown                                                                                                                         
    lock.acquire()        

using the we switch works few seconds and crash again.
Have to restart in in terminal, any ideas?

temporary work around would be to delete the imsi.db

**Comment by ninjhacks** [comment]
you can try by removing self before imsi_id at line 109 possibly it's will work or if this error happing without capturing new traffic means if I can replicate this issue just by having your db file then I will check if it's possible for you to share db file here or at ninjhacks@protonmail.com .

**Comment by darkhacknet** [comment]
> you can try by removing self before imsi_id at line 109 possibly it's will work or if this error happing without capturing new traffic means if I can replicate this issue just by having your db file then I will check if it's possible for you to share db file here or at [ninjhacks@protonmail.com](mailto:ninjhacks@protonmail.com) .

Hey Dude! =D I have all set up but... my kal command and livemon are not displaying results, could you please help ? Im using hackrf
